[program:t4jam-meta-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/demo-digmartools.prosesin.id
command=/usr/bin/php /var/www/demo-digmartools.prosesin.id/artisan queue:work database --queue=meta,default --sleep=3 --tries=3 --timeout=700 --memory=256 --max-time=3600
user=www-data
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=750
redirect_stderr=true
stdout_logfile=/var/www/demo-digmartools.prosesin.id/storage/logs/queue-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
